version: '3'
services:
  load_balancer:
    build:
      context: ./load-balancer
    ports:
     - "443:443"
    environment:
     - KEYCLOAK_FQDN=${KEYCLOAK_FQDN}
     - RESOURCE_FQDN=${RESOURCE_FQDN}
     - CONFORMANCE_SUITE_FQDN=${CONFORMANCE_SUITE_FQDN}
    depends_on:
     - keycloak
     - api_gateway_nginx
    networks:
      default:
        aliases:
         - ${KEYCLOAK_FQDN}
         - ${RESOURCE_FQDN}
      conformance-suite_default:
        aliases:
         - ${KEYCLOAK_FQDN}
         - ${RESOURCE_FQDN}
  keycloak:
    build:
      context: ./keycloak
    volumes:
     - ./https/server.pem:/etc/x509/https/tls.crt
     - ./https/server-key.pem:/etc/x509/https/tls.key
     - ./https/client-ca.pem:/etc/x509/https/client-ca.crt
#     - ../bin/keycloak-conformance-test:/opt/jboss/keycloak
    ports:
     - "8787:8787"
    environment:
     - KEYCLOAK_USER=${KEYCLOAK_USER}
     - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
    command: "-b 0.0.0.0 -Djboss.socket.binding.port-offset=1000 --debug -Dkeycloak.profile=preview"
  api_gateway_nginx:
    build:
      context: ./api-gateway-nginx
    volumes:
     - ./https/server.pem:/etc/x509/https/tls.crt
     - ./https/server-key.pem:/etc/x509/https/tls.key
     - ./https/client-ca.pem:/etc/x509/https/client-ca.crt
     - ./https/ca.pem:/usr/local/share/ca-certificates/keycloak-fapi-ca.pem
    environment:
     - SERVER_NAME=${RESOURCE_FQDN}
     - INTROSPECTION_ENDPOINT_URL=https://${KEYCLOAK_FQDN}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/token/introspect
     # JWT access token veirfication can't pass reuse-authorisation-code case
     # - DISCOVERY_URL=https://${KEYCLOAK_FQDN}/auth/realms/${KEYCLOAK_REALM}/.well-known/openid-configuration
     - CLIENT_SECRET=2ef90464-b0fc-4e06-965d-19ef671a3e22
    depends_on:
     - resource_server
  resource_server:
    build:
      context: ./resource-server
  client_jwks_server:
    build:
      context: ./client_private_keys
    volumes:
     - ./client_private_keys:/keys
    command: /keys

networks:
  conformance-suite_default:
    external: true

